name: CI pipeline

on:
  push:
    branches: [feature/deploy-project] # adapte si ta branche s'appelle master ou autre
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-imc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-imc
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: front-imc/dist/
          if-no-files-found: error
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-imc
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: front-imc/dist

      - name: List build-Artefacts
        run: ls -al

  package:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-imc
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: front-imc/dist

      - name: List build-Artefacts
        run: ls -al

  build_image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-imc
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: front-imc/dist

      - name: List build-Artefacts
        run: ls -al

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front-imc
    needs: build_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: front-imc/dist

      - name: List build-Artefacts
        run: ls -al
